"""
Builds a clean release folder for HFDM Thermal Solver.

Copies the source tree and the test suite, and nothing else. The exclusion list
is explicit rather than implicit: a release that quietly carries a stale
__pycache__, a previous release folder or a LibreOffice lock file is a release
nobody can reproduce.

Usage:
    python prepare_release.py
    python prepare_release.py --version 2.1 --verify
"""

import argparse
import os
import shutil
import subprocess
import sys

import config

VERSION = config.VERSION

#: Everything that must never reach a release, matched against the file or
#: directory name by shutil.ignore_patterns.
JUNK_PATTERNS = (
    "__pycache__", "*.py[cod]", "*$py.class",
    ".pytest_cache", ".coverage", "htmlcov",
    ".git", ".gitignore", ".venv", "venv", "env", "ENV", ".env",
    "build", "dist", "*.spec", "*.exe", "*.manifest",
    "HFDM_Release_*",
    ".~lock.*",          # LibreOffice leaves these next to an open CSV
    ".vscode", ".idea", "*.swp",
)

#: Image extensions that are screenshots at the top level but legitimate
#: fixtures inside tests/, so they are filtered per-location, not globally.
IMAGE_SUFFIXES = (".png", ".jpg", ".jpeg", ".gif", ".bmp")

#: Non-Python files carried alongside the sources.
EXTRA_FILES = ("README.md", "requirements.txt", "LICENSE")


def _ignore_junk(directory, names):
    """shutil.copytree filter: junk patterns, and nothing else."""
    return set(shutil.ignore_patterns(*JUNK_PATTERNS)(directory, names))


def prepare_release(version=VERSION, source_dir=None, verify=False):
    source_dir = os.path.abspath(source_dir or ".")
    release_name = f"HFDM_Release_v{version}"
    release_dir = os.path.join(source_dir, release_name)

    print(f"HFDM Thermal Solver - building {release_name}")
    print(f"  source: {source_dir}")

    if os.path.exists(release_dir):
        shutil.rmtree(release_dir)
        print(f"  cleaned existing {release_name}/")
    os.makedirs(release_dir)

    copied, skipped = [], []

    # --- Python sources -----------------------------------------------------
    for name in sorted(os.listdir(source_dir)):
        path = os.path.join(source_dir, name)
        if os.path.isfile(path) and name.endswith(".py"):
            shutil.copy2(path, release_dir)
            copied.append(name)

    # --- Documentation and dependency manifest ------------------------------
    for name in EXTRA_FILES:
        path = os.path.join(source_dir, name)
        if os.path.isfile(path):
            shutil.copy2(path, release_dir)
            copied.append(name)
        else:
            skipped.append(f"{name} (not present in the source tree)")

    # --- Test suite, fixtures included --------------------------------------
    tests_src = os.path.join(source_dir, "tests")
    if os.path.isdir(tests_src):
        shutil.copytree(tests_src, os.path.join(release_dir, "tests"),
                        ignore=_ignore_junk)
        for root, _dirs, files in os.walk(os.path.join(release_dir, "tests")):
            for name in files:
                copied.append(os.path.relpath(os.path.join(root, name), release_dir))
    else:
        skipped.append("tests/ (not present in the source tree)")

    # --- Report what was deliberately left behind ---------------------------
    for name in sorted(os.listdir(source_dir)):
        if name == release_name:
            continue
        path = os.path.join(source_dir, name)
        suffix = os.path.splitext(name)[1].lower()
        if name.startswith("HFDM_Release_"):
            skipped.append(f"{name}/ (previous release)")
        elif name in ("build", "dist"):
            skipped.append(f"{name}/ (build output)")
        elif name in ("__pycache__", ".pytest_cache", ".git"):
            skipped.append(f"{name}/ (cache / VCS)")
        elif suffix == ".spec":
            skipped.append(f"{name} (PyInstaller spec, regenerated by build_exe)")
        elif suffix in IMAGE_SUFFIXES and os.path.isfile(path):
            skipped.append(f"{name} (top-level screenshot)")

    _assert_clean(release_dir)

    # --- Summary ------------------------------------------------------------
    total = 0
    print(f"\n  {len(copied)} file(s) copied into {release_name}/\n")
    for name in sorted(copied):
        size = os.path.getsize(os.path.join(release_dir, name))
        total += size
        print(f"    {name:<50} {size:>9,} B")
    print(f"    {'':<50} {'-' * 11}")
    print(f"    {'TOTAL':<50} {total:>9,} B")

    if skipped:
        print("\n  deliberately excluded:")
        for name in sorted(set(skipped)):
            print(f"    - {name}")

    if verify:
        _verify(release_dir)
        _assert_clean(release_dir)

    print(f"\nRelease ready: {release_dir}")
    return release_dir


def _assert_clean(release_dir):
    """Fails loudly if anything from JUNK_PATTERNS made it into the release."""
    leaked = []
    for root, dirs, files in os.walk(release_dir):
        for name in list(dirs) + files:
            rel = os.path.relpath(os.path.join(root, name), release_dir)
            if (name in ("__pycache__", ".pytest_cache", ".git")
                    or name.startswith(".~lock.")
                    or name.startswith("HFDM_Release_")
                    or name.endswith((".pyc", ".spec", ".exe"))):
                leaked.append(rel)
    if leaked:
        raise RuntimeError(f"Junk leaked into the release: {sorted(leaked)}")


def _snapshot(release_dir):
    """Every path currently under release_dir, relative."""
    found = set()
    for root, dirs, files in os.walk(release_dir):
        for name in list(dirs) + files:
            found.add(os.path.relpath(os.path.join(root, name), release_dir))
    return found


def _verify(release_dir):
    """
    Imports the release and runs its own test suite from inside it.

    The suite writes files into its working directory - test_visualization
    saves probe_history.png - so the folder is snapshotted first and anything
    the run created is removed afterwards. Deleting a known list of caches was
    not enough: the first version of this script shipped that PNG.
    """
    print("\n  verifying the release in place...")
    before = _snapshot(release_dir)
    checks = (
        ("imports", [sys.executable, "-c",
                     "import main, gui, board_view, solver, data_loader, "
                     "visualization, config; print('all modules import')"]),
        ("pytest", [sys.executable, "-m", "pytest", "tests", "-q",
                    "-p", "no:cacheprovider", "--no-header"]),
    )
    env = dict(os.environ, QT_QPA_PLATFORM="offscreen", PYTHONIOENCODING="utf-8")
    for label, cmd in checks:
        result = subprocess.run(cmd, cwd=release_dir, capture_output=True,
                                text=True, env=env)
        tail = (result.stdout or result.stderr).strip().splitlines()
        print(f"    {label:<8} exit={result.returncode}  "
              f"{tail[-1] if tail else '(no output)'}")
        if result.returncode != 0:
            raise RuntimeError(f"Release verification failed at '{label}'")
    # Remove everything the run produced, whatever it was.
    created = sorted(_snapshot(release_dir) - before, key=len, reverse=True)
    for rel in created:
        path = os.path.join(release_dir, rel)
        if os.path.isdir(path):
            shutil.rmtree(path, ignore_errors=True)
        elif os.path.isfile(path):
            os.remove(path)
    if created:
        top = sorted({rel.split(os.sep)[0] for rel in created})
        print(f"    removed {len(created)} artefact(s) the run created: "
              f"{', '.join(top)}")
    leftover = _snapshot(release_dir) - before
    if leftover:
        raise RuntimeError(f"Verification artefacts survived cleanup: {leftover}")


def main():
    parser = argparse.ArgumentParser(
        description="Build a clean HFDM Thermal Solver release folder.")
    parser.add_argument("--version", default=VERSION)
    parser.add_argument("--source",
                        default=os.path.dirname(os.path.abspath(__file__)))
    parser.add_argument("--verify", action="store_true",
                        help="import the release and run its tests from inside it")
    args = parser.parse_args()
    prepare_release(args.version, args.source, args.verify)


if __name__ == "__main__":
    main()
